name: Danger

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install gems
        run: |
          gem install bundler

      - name: Run Danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bundle exec danger

